% Program Q2_29
clf;
h = [3 1 4 1 5 9 2 6 5 4 -3 -1 -4 -1 -5]; % impulse response
x = [0 1 2 1 0 -1 -2 -1 0 1]; % input sequence
y = conv(h, x);
n = 0:length(h) + length(x) - 2;
subplot(2, 1, 1);
stem(n, y);
xlabel('Time index n'); ylabel('Amplitude');
title('Output Obtained by Convolution'); grid;
x1 = [x zeros(1, length(h) - 1)];
y1 = filter(h, 1, x1);
subplot(2, 1, 2);
stem(n, y1);
xlabel('Time index n'); ylabel('Amplitude');
title('Output Generated by Filtering'); grid;
